#!/bin/bash

SCRIPT_NAME=${0##*/}
SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
MACHINE_TYPE=$(uname -m)
if [ ${MACHINE_TYPE} == 'x86_64' ]; then
  "${SCRIPT_DIR}/${SCRIPT_NAME}_x64" "$@"
else
  "${SCRIPT_DIR}/${SCRIPT_NAME}_x86" "$@"
fi
